<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Country;
class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries =[
            [
              'sort'=>'AF',
              'country_name'=>'Afghanistan',
            ],
            [
              'sort'=>'AL',
              'country_name'=>'Albania',
            ],
            [
              'sort'=>'DZ',
              'country_name'=>'Algeria',
                ],
        [
              'sort'=>'AS',
              'country_name'=>'American Samoa',
                ],
        [
              'sort'=>'AD',
              'country_name'=>'Andorra',
                ],
        [
              'sort'=>'AO',
              'country_name'=>'Angola',
                ],
        [
              'sort'=>'AI',
              'country_name'=>'Anguilla',
                ],
        [
              'sort'=>'AQ',
              'country_name'=>'Antarctica',
                ],
        [
              'sort'=>'AG',
              'country_name'=>'Antigua And Barbuda',
                ],
        [
              'sort'=>'AR',
              'country_name'=>'Argentina',
                ],
        [
              'sort'=>'AM',
              'country_name'=>'Armenia',
                ],
        [
              'sort'=>'AW',
              'country_name'=>'Aruba',
                ],
        [
              'sort'=>'AU',
              'country_name'=>'Australia',
                ],
        [
              'sort'=>'AT',
              'country_name'=>'Austria',
                ],
        [
              'sort'=>'AZ',
              'country_name'=>'Azerbaijan',
                ],
        [
              'sort'=>'BS',
              'country_name'=>'Bahamas The',
                ],
        [
              'sort'=>'BH',
              'country_name'=>'Bahrain',
                ],
        [
              'sort'=>'BD',
              'country_name'=>'Bangladesh',
                ],
        [
              'sort'=>'BB',
              'country_name'=>'Barbados',
                ],
        [
              'sort'=>'BY',
              'country_name'=>'Belarus',
                ],
        [
              'sort'=>'BE',
              'country_name'=>'Belgium',
                ],
        [
              'sort'=>'BZ',
              'country_name'=>'Belize',
                ],
        [
              'sort'=>'BJ',
              'country_name'=>'Benin',
                ],
        [
              'sort'=>'BM',
              'country_name'=>'Bermuda',
                ],
        [
              'sort'=>'BT',
              'country_name'=>'Bhutan',
                ],
        [
              'sort'=>'BO',
              'country_name'=>'Bolivia',
                ],
        [
              'sort'=>'BA',
              'country_name'=>'Bosnia and Herzegovina',
                ],
        [
              'sort'=>'BW',
              'country_name'=>'Botswana',
                ],
        [
              'sort'=>'BV',
              'country_name'=>'Bouvet Island',
                ],
        [
              'sort'=>'BR',
              'country_name'=>'Brazil',
                ],
        [
              'sort'=>'IO',
              'country_name'=>'British Indian Ocean Territory',
                ],
        [
              'sort'=>'BN',
              'country_name'=>'Brunei',
                ],
        [
              'sort'=>'BG',
              'country_name'=>'Bulgaria',
                ],
        [
              'sort'=>'BF',
              'country_name'=>'Burkina Faso',
                ],
        [
              'sort'=>'BI',
              'country_name'=>'Burundi',
                ],
        [
              'sort'=>'KH',
              'country_name'=>'Cambodia',
                ],
        [
              'sort'=>'CM',
              'country_name'=>'Cameroon',
                ],
        [
              'sort'=>'CA',
              'country_name'=>'Canada',
                ],
        [
              'sort'=>'CV',
              'country_name'=>'Cape Verde',
                ],
        [
              'sort'=>'KY',
              'country_name'=>'Cayman Islands',
                ],
        [
              'sort'=>'CF',
              'country_name'=>'Central African Republic',
                ],
        [
              'sort'=>'TD',
              'country_name'=>'Chad',
                ],
        [
              'sort'=>'CL',
              'country_name'=>'Chile',
                ],
        [
              'sort'=>'CN',
              'country_name'=>'China',
                ],
        [
              'sort'=>'CX',
              'country_name'=>'Christmas Island',
                ],
        [
              'sort'=>'CC',
              'country_name'=>'Cocos (Keeling) Islands',
                ],
        [
              'sort'=>'CO',
              'country_name'=>'Colombia',
                ],
        [
              'sort'=>'KM',
              'country_name'=>'Comoros',
                ],
        [
              'sort'=>'CG',
              'country_name'=>'Republic Of The Congo',
                ],
        [
              'sort'=>'CD',
              'country_name'=>'Democratic Republic Of The Congo',
                ],
        [
              'sort'=>'CK',
              'country_name'=>'Cook Islands',
                ],
        [
              'sort'=>'CR',
              'country_name'=>'Costa Rica',
                ],
        [
              'sort'=>'CI',
              'country_name'=>'Cote D Ivoire (Ivory Coast)',
                ],
        [
              'sort'=>'HR',
              'country_name'=>'Croatia (Hrvatska)',
                ],
        [
              'sort'=>'CU',
              'country_name'=>'Cuba',
                ],
        [
              'sort'=>'CY',
              'country_name'=>'Cyprus',
                ],
        [
              'sort'=>'CZ',
              'country_name'=>'Czech Republic',
                ],
        [
              'sort'=>'DK',
              'country_name'=>'Denmark',
                ],
        [
              'sort'=>'DJ',
              'country_name'=>'Djibouti',
                ],
        [
              'sort'=>'DM',
              'country_name'=>'Dominica',
                ],
        [
              'sort'=>'DO',
              'country_name'=>'Dominican Republic',
                ],
        [
              'sort'=>'TP',
              'country_name'=>'East Timor',
                ],
        [
              'sort'=>'EC',
              'country_name'=>'Ecuador',
                ],
        [
              'sort'=>'EG',
              'country_name'=>'Egypt',
                ],
        [
              'sort'=>'SV',
              'country_name'=>'El Salvador',
                ],
        [
              'sort'=>'GQ',
              'country_name'=>'Equatorial Guinea',
                ],
        [
              'sort'=>'ER',
              'country_name'=>'Eritrea',
                ],
        [
              'sort'=>'EE',
              'country_name'=>'Estonia',
                ],
        [
              'sort'=>'ET',
              'country_name'=>'Ethiopia',
                ],
        [
              'sort'=>'XA',
              'country_name'=>'External Territories of Australia',
                ],
        [
              'sort'=>'FK',
              'country_name'=>'Falkland Islands',
                ],
        [
              'sort'=>'FO',
              'country_name'=>'Faroe Islands',
                ],
        [
              'sort'=>'FJ',
              'country_name'=>'Fiji Islands',
                ],
        [
              'sort'=>'FI',
              'country_name'=>'Finland',
                ],
        [
              'sort'=>'FR',
              'country_name'=>'France',
                ],
        [
              'sort'=>'GF',
              'country_name'=>'French Guiana',
                ],
        [
              'sort'=>'PF',
              'country_name'=>'French Polynesia',
                ],
        [
              'sort'=>'TF',
              'country_name'=>'French Southern Territories',
                ],
        [
              'sort'=>'GA',
              'country_name'=>'Gabon',
                ],
        [
              'sort'=>'GM',
              'country_name'=>'Gambia The',
                ],
        [
              'sort'=>'GE',
              'country_name'=>'Georgia',
                ],
        [
              'sort'=>'DE',
              'country_name'=>'Germany',
                ],
        [
              'sort'=>'GH',
              'country_name'=>'Ghana',
                ],
        [
              'sort'=>'GI',
              'country_name'=>'Gibraltar',
                ],
        [
              'sort'=>'GR',
              'country_name'=>'Greece',
                ],
        [
              'sort'=>'GL',
              'country_name'=>'Greenland',
                ],
        [
              'sort'=>'GD',
              'country_name'=>'Grenada',
                ],
        [
              'sort'=>'GP',
              'country_name'=>'Guadeloupe',
                ],
        [
              'sort'=>'GU',
              'country_name'=>'Guam',
                ],
        [
              'sort'=>'GT',
              'country_name'=>'Guatemala',
                ],
        [
              'sort'=>'XU',
              'country_name'=>'Guernsey and Alderney',
                ],
        [
              'sort'=>'GN',
              'country_name'=>'Guinea',
                ],
        [
              'sort'=>'GW',
              'country_name'=>'Guinea-Bissau',
                ],
        [
              'sort'=>'GY',
              'country_name'=>'Guyana',
                ],
        [
              'sort'=>'HT',
              'country_name'=>'Haiti',
                ],
        [
              'sort'=>'HM',
              'country_name'=>'Heard and McDonald Islands',
                ],
        [
              'sort'=>'HN',
              'country_name'=>'Honduras',
                ],
        [
              'sort'=>'HK',
              'country_name'=>'Hong Kong S.A.R.',
                ],
        [
              'sort'=>'HU',
              'country_name'=>'Hungary',
                ],
        [
              'sort'=>'IS',
              'country_name'=>'Iceland',
                ],
        [
              'sort'=>'IN',
              'country_name'=>'India',
                ],
        [
              'sort'=>'country_id',
              'country_name'=>'Indonesia',
                ],
        [
              'sort'=>'IR',
              'country_name'=>'Iran',
                ],
        [
              'sort'=>'IQ',
              'country_name'=>'Iraq',
                ],
        [
              'sort'=>'IE',
              'country_name'=>'Ireland',
                ],
        [
              'sort'=>'IL',
              'country_name'=>'Israel',
                ],
        [
              'sort'=>'IT',
              'country_name'=>'Italy',
                ],
        [
              'sort'=>'JM',
              'country_name'=>'Jamaica',
                ],
        [
              'sort'=>'JP',
              'country_name'=>'Japan',
                ],
        [
              'sort'=>'XJ',
              'country_name'=>'Jersey',
                ],
        [
              'sort'=>'JO',
              'country_name'=>'Jordan',
                ],
        [
              'sort'=>'KZ',
              'country_name'=>'Kazakhstan',
                ],
        [
              'sort'=>'KE',
              'country_name'=>'Kenya',
                ],
        [
              'sort'=>'KI',
              'country_name'=>'Kiribati',
                ],
        [
              'sort'=>'KP',
              'country_name'=>'Korea North',
                ],
        [
              'sort'=>'KR',
              'country_name'=>'Korea South',
                ],
        [
              'sort'=>'KW',
              'country_name'=>'Kuwait',
                ],
        [
              'sort'=>'KG',
              'country_name'=>'Kyrgyzstan',
                ],
        [
              'sort'=>'LA',
              'country_name'=>'Laos',
                ],
        [
              'sort'=>'LV',
              'country_name'=>'Latvia',
                ],
        [
              'sort'=>'LB',
              'country_name'=>'Lebanon',
                ],
        [
              'sort'=>'LS',
              'country_name'=>'Lesotho',
                ],
        [
              'sort'=>'LR',
              'country_name'=>'Liberia',
                ],
        [
              'sort'=>'LY',
              'country_name'=>'Libya',
                ],
        [
              'sort'=>'LI',
              'country_name'=>'Liechtenstein',
                ],
        [
              'sort'=>'LT',
              'country_name'=>'Lithuania',
                ],
        [
              'sort'=>'LU',
              'country_name'=>'Luxembourg',
                ],
        [
              'sort'=>'MO',
              'country_name'=>'Macau S.A.R.',
                ],
        [
              'sort'=>'MK',
              'country_name'=>'Macedonia',
                ],
        [
              'sort'=>'MG',
              'country_name'=>'Madagascar',
                ],
        [
              'sort'=>'MW',
              'country_name'=>'Malawi',
                ],
        [
              'sort'=>'MY',
              'country_name'=>'Malaysia',
                ],
        [
              'sort'=>'MV',
              'country_name'=>'Maldives',
                ],
        [
              'sort'=>'ML',
              'country_name'=>'Mali',
                ],
        [
              'sort'=>'MT',
              'country_name'=>'Malta',
                ],
        [
              'sort'=>'XM',
              'country_name'=>'Man (Isle of)',
                ],
        [
              'sort'=>'MH',
              'country_name'=>'Marshall Islands',
                ],
        [
              'sort'=>'MQ',
              'country_name'=>'Martinique',
                ],
        [
              'sort'=>'MR',
              'country_name'=>'Mauritania',
                ],
        [
              'sort'=>'MU',
              'country_name'=>'Mauritius',
                ],
        [
              'sort'=>'YT',
              'country_name'=>'Mayotte',
                ],
        [
              'sort'=>'MX',
              'country_name'=>'Mexico',
                ],
        [
              'sort'=>'FM',
              'country_name'=>'Micronesia',
                ],
        [
              'sort'=>'MD',
              'country_name'=>'Moldova',
                ],
        [
              'sort'=>'MC',
              'country_name'=>'Monaco',
                ],
        [
              'sort'=>'MN',
              'country_name'=>'Mongolia',
                ],
        [
              'sort'=>'MS',
              'country_name'=>'Montserrat',
                ],
        [
              'sort'=>'MA',
              'country_name'=>'Morocco',
                ],
        [
              'sort'=>'MZ',
              'country_name'=>'Mozambique',
                ],
        [
              'sort'=>'MM',
              'country_name'=>'Myanmar',
                ],
        [
              'sort'=>'NA',
              'country_name'=>'Namibia',
                ],
        [
              'sort'=>'NR',
              'country_name'=>'Nauru',
                ],
        [
              'sort'=>'NP',
              'country_name'=>'Nepal',
                ],
        [
              'sort'=>'AN',
              'country_name'=>'Netherlands Antilles',
                ],
        [
              'sort'=>'NL',
              'country_name'=>'Netherlands The',
                ],
        [
              'sort'=>'NC',
              'country_name'=>'New Caledonia',
                ],
        [
              'sort'=>'NZ',
              'country_name'=>'New Zealand',
                ],
        [
              'sort'=>'NI',
              'country_name'=>'Nicaragua',
                ],
        [
              'sort'=>'NE',
              'country_name'=>'Niger',
                ],
        [
              'sort'=>'NG',
              'country_name'=>'Nigeria',
                ],
        [
              'sort'=>'NU',
              'country_name'=>'Niue',
                ],
        [
              'sort'=>'NF',
              'country_name'=>'Norfolk Island',
                ],
        [
              'sort'=>'MP',
              'country_name'=>'Northern Mariana Islands',
                ],
        [
              'sort'=>'NO',
              'country_name'=>'Norway',
                ],
        [
              'sort'=>'OM',
              'country_name'=>'Oman',
                ],
        [
              'sort'=>'PK',
              'country_name'=>'Pakistan',
                ],
        [
              'sort'=>'PW',
              'country_name'=>'Palau',
                ],
        [
              'sort'=>'PS',
              'country_name'=>'Palestinian Territory Occupied',
                ],
        [
              'sort'=>'PA',
              'country_name'=>'Panama',
                ],
        [
              'sort'=>'PG',
              'country_name'=>'Papua new Guinea',
                ],
        [
              'sort'=>'PY',
              'country_name'=>'Paraguay',
                ],
        [
              'sort'=>'PE',
              'country_name'=>'Peru',
                ],
        [
              'sort'=>'PH',
              'country_name'=>'Philippines',
                ],
        [
              'sort'=>'PN',
              'country_name'=>'Pitcairn Island',
                ],
        [
              'sort'=>'PL',
              'country_name'=>'Poland',
                ],
        [
              'sort'=>'PT',
              'country_name'=>'Portugal',
                ],
        [
              'sort'=>'PR',
              'country_name'=>'Puerto Rico',
                ],
        [
              'sort'=>'QA',
              'country_name'=>'Qatar',
                ],
        [
              'sort'=>'RE',
              'country_name'=>'Reunion',
                ],
        [
              'sort'=>'RO',
              'country_name'=>'Romania',
                ],
        [
              'sort'=>'RU',
              'country_name'=>'Russia',
                ],
        [
              'sort'=>'RW',
              'country_name'=>'Rwanda',
                ],
        [
              'sort'=>'SH',
              'country_name'=>'Saint Helena',
                ],
        [
              'sort'=>'KN',
              'country_name'=>'Saint Kitts And Nevis',
                ],
        [
              'sort'=>'LC',
              'country_name'=>'Saint Lucia',
                ],
        [
              'sort'=>'PM',
              'country_name'=>'Saint Pierre and Miquelon',
                ],
        [
              'sort'=>'VC',
              'country_name'=>'Saint Vincent And The Grenadines',
                ],
        [
              'sort'=>'WS',
              'country_name'=>'Samoa',
                ],
        [
              'sort'=>'SM',
              'country_name'=>'San Marino',
                ],
        [
              'sort'=>'ST',
              'country_name'=>'Sao Tome and Principe',
                ],
        [
              'sort'=>'SA',
              'country_name'=>'Saudi Arabia',
                ],
        [
              'sort'=>'SN',
              'country_name'=>'Senegal',
                ],
        [
              'sort'=>'RS',
              'country_name'=>'Serbia',
                ],
        [
              'sort'=>'SC',
              'country_name'=>'Seychelles',
                ],
        [
              'sort'=>'SL',
              'country_name'=>'Sierra Leone',
                ],
        [
              'sort'=>'SG',
              'country_name'=>'Singapore',
                ],
        [
              'sort'=>'SK',
              'country_name'=>'Slovakia',
                ],
        [
              'sort'=>'SI',
              'country_name'=>'Slovenia',
                ],
        [
              'sort'=>'XG',
              'country_name'=>'Smaller Territories of the UK',
                ],
        [
              'sort'=>'SB',
              'country_name'=>'Solomon Islands',
                ],
        [
              'sort'=>'SO',
              'country_name'=>'Somalia',
                ],
        [
              'sort'=>'ZA',
              'country_name'=>'South Africa',
                ],
        [
              'sort'=>'GS',
              'country_name'=>'South Georgia',
                ],
        [
              'sort'=>'SS',
              'country_name'=>'South Sudan',
                ],
        [
              'sort'=>'ES',
              'country_name'=>'Spain',
                ],
        [
              'sort'=>'LK',
              'country_name'=>'Sri Lanka',
                ],
        [
              'sort'=>'SD',
              'country_name'=>'Sudan',
                ],
        [
              'sort'=>'SR',
              'country_name'=>'Suricountry_name',
                ],
        [
              'sort'=>'SJ',
              'country_name'=>'Svalbard And Jan Mayen Islands',
                ],
        [
              'sort'=>'SZ',
              'country_name'=>'Swaziland',
                ],
        [
              'sort'=>'SE',
              'country_name'=>'Sweden',
                ],
        [
              'sort'=>'CH',
              'country_name'=>'Switzerland',
                ],
        [
              'sort'=>'SY',
              'country_name'=>'Syria',
                ],
        [
              'sort'=>'TW',
              'country_name'=>'Taiwan',
                ],
        [
              'sort'=>'TJ',
              'country_name'=>'Tajikistan',
                ],
        [
              'sort'=>'TZ',
              'country_name'=>'Tanzania',
                ],
        [
              'sort'=>'TH',
              'country_name'=>'Thailand',
                ],
        [
              'sort'=>'TG',
              'country_name'=>'Togo',
                ],
        [
              'sort'=>'TK',
              'country_name'=>'Tokelau',
                ],
        [
              'sort'=>'TO',
              'country_name'=>'Tonga',
                ],
        [
              'sort'=>'TT',
              'country_name'=>'Trincountry_idad And Tobago',
                ],
        [
              'sort'=>'TN',
              'country_name'=>'Tunisia',
                ],
        [
              'sort'=>'TR',
              'country_name'=>'Turkey',
                ],
        [
              'sort'=>'TM',
              'country_name'=>'Turkmenistan',
                ],
        [
              'sort'=>'TC',
              'country_name'=>'Turks And Caicos Islands',
                ],
        [
              'sort'=>'TV',
              'country_name'=>'Tuvalu',
                ],
        [
              'sort'=>'UG',
              'country_name'=>'Uganda',
                ],
        [
              'sort'=>'UA',
              'country_name'=>'Ukraine',
                ],
        [
              'sort'=>'AE',
              'country_name'=>'United Arab Emirates',
                ],
        [
              'sort'=>'GB',
              'country_name'=>'United Kingdom',
                ],
        [
              'sort'=>'US',
              'country_name'=>'United States',
                ],
        [
              'sort'=>'UM',
              'country_name'=>'United States Minor Outlying Islands',
                ],
        [
              'sort'=>'UY',
              'country_name'=>'Uruguay',
                ],
        [
              'sort'=>'UZ',
              'country_name'=>'Uzbekistan',
                ],
        [
              'sort'=>'VU',
              'country_name'=>'Vanuatu',
                ],
        [
              'sort'=>'VA',
              'country_name'=>'Vatican City State (Holy See)',
                ],
        [
              'sort'=>'VE',
              'country_name'=>'Venezuela',
                ],
        [
              'sort'=>'VN',
              'country_name'=>'Vietnam',
                ],
        [
              'sort'=>'VG',
              'country_name'=>'Virgin Islands (British)',
                ],
        [
              'sort'=>'VI',
              'country_name'=>'Virgin Islands (US)',
                ],
        [
              'sort'=>'WF',
              'country_name'=>'Wallis And Futuna Islands',
                ],
        [
              'sort'=>'EH',
              'country_name'=>'Western Sahara',
                ],
        [
              'sort'=>'YE',
              'country_name'=>'Yemen',
                ],
        [
              'sort'=>'YU',
              'country_name'=>'Yugoslavia',
                ],
        [
              'sort'=>'ZM',
              'country_name'=>'Zambia',
                ],
        [
              'sort'=>'ZW',
              'country_name'=>'Zimbabwe',
                ],
          ];
           Country::insert($countries);
        }
}
